// "use client";
import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";
// import { useEffect, useState } from "react";

// Server component
export const metadata = {
  title: "Web tutorials",
  description: "Generated by mykuromi",
};

export default async function RootLayout({ children }) {
  /*
  const [topics, setTopics] = useState([]);
  // Client component
  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((resp) => resp.json())
      .then((result) => {
        setTopics(result);
      });
  });
  */

  const resp = await fetch(process.env.API_URL + "topics", {
    next: { revalidate: 0, cache: "no-store" }, // no cache
  });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
